// conformance/framework-ports/ports/src/react-reference-counter.tsx
import { useEffect } from "react";
import { useAtomValue } from "@effect/atom-react";
import { referenceText, referenceTitle, type HostLifecycle } from "./reference-counter.js";
import type { ReferenceRegistry } from "./reference-registry.js";

type Props = Readonly<{ owner: ReferenceRegistry; onLifecycle: (event: HostLifecycle) => void }>;

export function ReactReferenceCounter({ owner, onLifecycle }: Props) {
  const state = useAtomValue(owner.state);
  useEffect(() => {
    onLifecycle("mount");
    return () => onLifecycle("unmount");
  }, [onLifecycle]);
  useEffect(() => { document.title = referenceTitle(state); }, [state]);
  return (
    <section data-reference="react-atom">
      <output data-role="count" aria-live="polite">{referenceText(state)}</output>
      <button type="button" data-action="decrement" aria-label="Decrement" onClick={() => owner.dispatch("ClickedDecrement")}>-</button>
      <button type="button" data-action="reset" onClick={() => owner.dispatch("ClickedReset")}>Reset</button>
      <button type="button" data-action="increment" aria-label="Increment" onClick={() => owner.dispatch("ClickedIncrement")}>+</button>
    </section>
  );
}

// conformance/framework-ports/ports/src/solid-reference-counter.ts
import { createEffect, createSignal, onCleanup } from "solid-js";
import h from "@solidjs/h";
import { referenceText, referenceTitle, type HostLifecycle } from "./reference-counter.js";
import type { ReferenceRegistry } from "./reference-registry.js";

export function SolidReferenceCounter(owner: ReferenceRegistry, onLifecycle: (event: HostLifecycle) => void) {
  const [state, setState] = createSignal(owner.registry.get(owner.state));
  const cancel = owner.registry.subscribe(owner.state, value => setState(value));
  onLifecycle("mount");
  onCleanup(() => { cancel(); onLifecycle("unmount"); });
  createEffect(() => referenceTitle(state()), title => { document.title = title; });
  const element = h(
    "section", { "data-reference": "solid-effect" },
    h("output", { "data-role": "count", "aria-live": "polite" }, () => referenceText(state())),
    h("button", { type: "button", "data-action": "decrement", "aria-label": "Decrement", onClick: () => owner.dispatch("ClickedDecrement") }, "-"),
    h("button", { type: "button", "data-action": "reset", onClick: () => owner.dispatch("ClickedReset") }, "Reset"),
    h("button", { type: "button", "data-action": "increment", "aria-label": "Increment", onClick: () => owner.dispatch("ClickedIncrement") }, "+")
  );
  return typeof element === "function" ? element() : element;
}
